server:
  port: 8888
logging:
  level:
    com.wj: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myroot
    username: root
    password: root
  redis:
    database: 0
    password:
    port: 6379
    host: 127.0.0.1
  mvc:
    view:
      prefix: /
      suffix: .jsp

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl