server:
  port: 10000 #服务端口
spring:
  application:
    name: api-zuul #指定服务名
zuul:
  routes:
    user-service: /us/** # 这里是自己指定的映射路径# 这里是路由id，随意写
    user-customer: /user-customer/**
  #ignored-services: #指定对外不公开的服务列表
   # - user-service
      # path: /user-service/** # 这里是映射路径
      #serviceId: user-service # 指定服务名称
      # url: http://127.0.0.1:9001 # 映射路径对应的实际url地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka # 配置eureka
  instance: #本机
    prefer-ip-address: true
    ip-address: 127.0.0.1
